### ISSUE TITLE
[Question] Is the optimal algorithm of cotengrust the same with contengra?

### ISSUE THREAD

**Issue by lucky9-cyou** [jcmgray/cotengrust#1]
I noticed that they seemed to be from two different articles， but they have similar name. Thanks for your answer.

**Comment by jcmgray** [comment]
Cotengrust implements the same (recently added) optimal algorithm in cotengra, they both follow and reference the same paper I believe (Pfeifer et al).

**Comment by lucky9-cyou** [comment]
Got it! Thanks for your reply
